### ISSUE TITLE
Detect `op` failure due to throttling

### ISSUE THREAD

**Issue by zcutlip** [zcutlip/pyonepassword#137]
It's possible to hit a cap for number of requests, especially when using service accounts. We should scrape stderr to look for this failure and raise an appropriate exception

An example of the message:
```
[ERROR] 2023/06/26 11:55:32 (429) Too Many Requests: You've reached the maximum number of this type of requests this service account is allowed to make. Please retry in 58 minutes or try other requests.
```

**Comment by jchan-legendpower** [comment]
It seems that on Windows using the desktop app the message can also be: 
```
[ERROR] 2024/12/13 15:48:08 connecting to desktop app: cannot connect to 1Password app, make sure it is running
```

Testing with the following script:
```py
import traceback
import logging
from pyonepassword import OP

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)

try:
    op = OP(logger=logger)
    exit(0)
except Exception as e:
    print(e)
    print(e.err_output)
    print(traceback.format_exc())
```

I often get:
```
DEBUG:__main__:Running: op --version
DEBUG:__main__:Running: op --format json account list
DEBUG:__main__:uses bio: True
DEBUG:__main__:Running: op --format json account list
'op' command failed
[ERROR] 2024/12/13 15:48:08 connecting to desktop app: cannot connect to 1Password app, make sure it is running
Traceback (most recent call last):
  File "C:\Users\JasperChan\AppData\Local\pypoetry\Cache\virtualenvs\legend-test-0EhuAPOU-py3.12\Lib\site-packages\pyonepassword\_op_cli.py", line 68, in _run_raw
    _ran.check_returncode()
  File "C:\Users\JasperChan\miniconda3\Lib\subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['op', '--format', 'json', 'account', 'list']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JasperChan\repos\legend_test\test_pyop_simple.py", line 9, in <module>
    op = OP(logger=logger)
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\JasperChan\AppData\Local\pypoetry\Cache\virtualenvs\legend-test-0EhuAPOU-py3.12\Lib\site-packages\pyonepassword\pyonepassword.py", line 123, in __init__
    super().__init__(vault=vault,
  File "C:\Users\JasperChan\AppData\Local\pypoetry\Cache\virtualenvs\legend-test-0EhuAPOU-py3.12\Lib\site-packages\pyonepassword\_op_commands.py", line 116, in __init__
    self._gather_facts()
  File "C:\Users\JasperChan\AppData\Local\pypoetry\Cache\virtualenvs\legend-test-0EhuAPOU-py3.12\Lib\site-packages\pyonepassword\_op_commands.py", line 259, in _gather_facts
    self._account_list = self._get_account_list(self.op_path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JasperChan\AppData\Local\pypoetry\Cache\virtualenvs\legend-test-0EhuAPOU-py3.12\Lib\site-packages\pyonepassword\_op_commands.py", line 274, in _get_account_list
    account_list_json = cls._signed_in_accounts(op_path, decode=decode)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JasperChan\AppData\Local\pypoetry\Cache\virtualenvs\legend-test-0EhuAPOU-py3.12\Lib\site-packages\pyonepassword\_op_commands.py", line 684, in _signed_in_accounts
    output = cls._run(account_list_argv,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JasperChan\AppData\Local\pypoetry\Cache\virtualenvs\legend-test-0EhuAPOU-py3.12\Lib\site-packages\pyonepassword\_op_cli.py", line 103, in _run
    output, _, _ = cls._run_raw(
                   ^^^^^^^^^^^^^
  File "C:\Users\JasperChan\AppData\Local\pypoetry\Cache\virtualenvs\legend-test-0EhuAPOU-py3.12\Lib\site-packages\pyonepassword\_op_cli.py", line 94, in _run_raw
    raise OPCmdFailedException(stderr_output, returncode) from err
pyonepassword.py_op_exceptions.OPCmdFailedException: 'op' command failed
```

This seems to happen most reliably when I cold start the desktop app (3 dot menu -> Quit, then start up again from Start menu).

I've noticed that if I call `OP()` in a loop, it usually eventually succeeds after about 2 minutes, but the exact time varies wildly.

I am pretty sure this is related to rate limiting, because with this script:
```py
from time import time, sleep
from subprocess import run

last_run = time()
timeout = 0

def do_run():
    global last_run
    while time() - last_run < timeout:
        sleep(0.001)
    run(["op", "--format", "json", "account", "list"], check=True)
    last_run = time()


start = time()
while True:
    try:
        do_run()
        do_run()
    except Exception:
        continue
    print(f"Finished in {time() - start}")
    exit(0)
```
I get similar behavior.
With `timeout` set to 0, the logs look like:
```
[
  {
    REDACTED
  }
]
[ERROR] 2024/12/13 15:55:44 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 15:55:44 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 15:55:45 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 15:55:45 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 15:55:45 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 15:55:45 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 15:55:45 connecting to desktop app: cannot connect to 1Password app, make sure it is running
...
[ERROR] 2024/12/13 16:01:20 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 16:01:20 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 16:01:20 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 16:01:20 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 16:01:21 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 16:01:21 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[
  {
    REDACTED
  }
]
[ERROR] 2024/12/13 16:01:21 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 16:01:21 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 16:01:22 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 16:01:22 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 16:01:22 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[ERROR] 2024/12/13 16:01:22 connecting to desktop app: cannot connect to 1Password app, make sure it is running
[
  {
    REDACTED
  }
]
[
  {
    REDACTED
  }
]
Finished in 340.5131034851074
```

Typically after it passes I can run the script again with 0 timeout and it will immediately succeed first try.

At least on my machine a timeout of 0.7s seems to be pretty reliable even immediately after a cold boot of the desktop app.

**Comment by zcutlip** [comment]
@jchan-legendpower this is interesting thank you for reporting this

I asked in the 1Password developers slack about the errors your seeing, and they think there must be some other issue for you, based on the error message.

Your timeout of 0.7s doesn't seem to be related to throttling. The rate limits are on an hourly and daily basis, rather than fractions of a second.

Here's more info:
https://developer.1password.com/docs/service-accounts/rate-limits

**Comment by jchan-legendpower** [comment]
The docs you linked are for rate limiting on service accounts, I'm seeing this issue when connecting to the desktop app which should be a local connection.
It seems like the desktop app itself is rate limiting/not responding fast enough to subsequent requests.

**Comment by zcutlip** [comment]
Yes that's correct. This particular issue is about server side rate limiting, which isn't what's happening to you.

In fact I wouldn't say what you're experiencing is rate limiting per se. I think probably what's happening is the repeated calls to `op` is DOSing whatever thread in the main app is responsible for IPC with `op` and messages are getting dropped. I don't really know how `op` talks to 1Password on windows or even how windows IPC works, but that's just a guess

I don't think this is the proper GH issue to address that, but what I can do is create another issue to address situations where `op` can't talk to the app. I think at the very least we could raise a specific exception, giving the caller the chance to back off briefly
