### ISSUE TITLE
Properly handle `op` config where "accounts" is null

### ISSUE THREAD

**Issue by nodomain** [zcutlip/pyonepassword#43]
Hi,

I unfortunately cannot get it to work even using the easiest examples.

```python
>>> from pyonepassword import OP
>>> op = OP()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/src/.venv/lib/python3.10/site-packages/pyonepassword/_py_op_deprecation.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "/path/to/src/.venv/lib/python3.10/site-packages/pyonepassword/pyonepassword.py", line 84, in __init__
    super().__init__(vault=vault,
  File "/path/to/src/.venv/lib/python3.10/site-packages/pyonepassword/_py_op_commands.py", line 102, in __init__
    self._gather_facts()
  File "/path/to/src/.venv/lib/python3.10/site-packages/pyonepassword/_py_op_commands.py", line 151, in _gather_facts
    self._op_config = OPCLIConfig()
  File "/path/to/src/.venv/lib/python3.10/site-packages/pyonepassword/_op_cli_config.py", line 66, in __init__
    accounts = self._initialize_account_objects()
  File "/path/to/src/.venv/lib/python3.10/site-packages/pyonepassword/_op_cli_config.py", line 94, in _initialize_account_objects
    for account_dict in account_list:
TypeError: 'NoneType' object is not iterable
```

```bash
# op --version
2.7.1
```

CLI seems to work:
```bash
# op account list
URL                       EMAIL                         USER ID
privateaccount.1password.com    privatemail@domain.tld    xxxxyyy
workaccount.1password.com     workmail@work.tld    zzzaaaa
```

We use 1Password with workaccount.1password.com in the Business Plan. I activated TouchID in the Developer Settings as described in the CLI docs.

Please help :-)

**Comment by zcutlip** [comment]
Thanks for the bug report. I'll look into it.

Did you install the latest release using `pip`, or did you install from GitHub?

**Comment by nodomain** [comment]
Thanks!

Installed via:

```bash
python3 -m pip install pyonepassword
```

**Comment by nodomain** [comment]
This is awesome. Thanks!

**Comment by zcutlip** [comment]
Okay, v3.2.1 should be in PyPI now. Let me know if this gets you going.  Thanks again for the bug report!

**Comment by nodomain** [comment]
It works, thanks so much!
